### ISSUE TITLE
 want to support optional fields

### ISSUE THREAD

**Issue by chensylz** [zaihui/ent-factory#17]
such as : 

`field.Int("print_times").Nillable().Optional().Comment("打印次数")`

now generate code:

`SetPrintTimes(data.PrintTimes)`

maybe the code could be `SetNillablePrintTimes(data.PrintTimes)`

**Comment by lxy1992** [comment]
It's a good question. I haven't meet it yet. It seems we need to identify the pointer field in the struct, then change the setter. I could provide some hints from chatgpt, you could try to contribute a PR.

![mhbjyTNXXt](https://user-images.githubusercontent.com/6184994/210939461-72c99200-2edc-4763-9cae-8d2eac981a96.png)
