### ISSUE TITLE
generate fail by not exist go file

### ISSUE THREAD

**Issue by li31727** [zaihui/ent-factory#19]
When no.go file with the same name is found in a folder under schemaPath, the whole program simply ends. No, I don't think this is reasonable. Although the console prints the error (file_name.go not exist). I thought I'd skip this faulty factories build section and prompt the user at the console that the Factories build is not there
（当schemaPath下文件夹未找到与文件夹同名的.go文件时，整个程序直接结束掉不，我认为这是不合理的。虽然控制台输出了该错误（file_name.go not exist)。我认为应该跳过这部分错误的factories生成部分，并在控制台提示用户该部分未生成）

**Comment by lxy1992** [comment]
Please provide an example for this situation, because usually the legal folder name has a same name go file in that path.

But, for this case, I think your proposal is reasonable. Thank you for mention it.

**Comment by li31727** [comment]
the  gen tree is （just focus on the schema folder）
├── gen
│   ├── entschema
│   │   ├── client.go
│   │   ├── config.go
│   │   ├── context.go
│   │   ├── ent.go
│   │   ├── enttest
│   │   │   └── enttest.go
│   │   ├── generate.go
│   │   ├── hook
│   │   │   └── hook.go
│   │   ├── membership
│   │   │   ├── membership.go
│   │   │   └── where.go
│   │   ├── migrate
│   │   │   ├── migrate.go
│   │   │   └── schema.go
│   │   ├── mutation.go
│   │   ├── predicate
│   │   │   └── predicate.go
│   │   ├── runtime
│   │   │   └── runtime.go
│   │   ├── runtime.go
│   │   ├── schema
│   │   │   ├── bytedanceapp.go
│   │   │   ├── utils.go
│   │   │   └── validator.go
│   │   └── tx.go
  the schema folder does not contain schema.go ,This results in only partial code generation and it reported this error：open /Users/zh/sdk/go1.16/demo/entdemo/ent/schema.go: no such file or directory

the code generation tree is 
│   └── testutils
│       ├── factories
│       │   └── common.go

I think the reason for generating some code may be related to the alphabetical order of file names.
This is my example: just fouce(schema folder and user folder)
├── ent
│   ├── client.go
│   ├── config.go
│   ├── context.go
│   ├── ent.go
│   ├── enttest
│   │   └── enttest.go
│   ├── generate.go
│   ├── hook
│   │   └── hook.go
│   ├── migrate
│   │   ├── migrate.go
│   │   └── schema.go
│   ├── mutation.go
│   ├── predicate
│   │   └── predicate.go
│   ├── runtime
│   │   └── runtime.go
│   ├── runtime.go
│   ├── schema
│   │   └── user.go
│   ├── tx.go
│   ├── user
│   │   ├── user.go
│   │   └── where.go
│   ├── user.go
│   ├── user_create.go
│   ├── user_delete.go
│   ├── user_query.go
│   └── user_update.go
├── factories
│   ├── common.go
│   └── userfactory
│       └── userfactory.go
 shemaPath is ent and  it's  working 。 
Although it reported this error：open /Users/zh/sdk/go1.16/demo/entdemo/ent/schema.go: no such file or directory

**Comment by li31727** [comment]
I think the mistake should be reported in this line https://github.com/zaihui/ent-factory/blob/2db20c3fb6dc5e90068983d80246cb4e0e52d6d0/cmd/generate.go#L255

**Comment by lxy1992** [comment]
@li31727 I get it. You are talking about the wrong schema path causes the generating error. It should return a reasonable error message. I will fix today. Thanks for providing such detail message. If I understand wrongly, please let me know.

**Comment by lxy1992** [comment]
Thank you for such details message, I understand it now. 
First, the schema Path not defines the definition path of human defined models, it defines the ent generated code path. 
Then, there is a misplace part of code in your `gen` Path. The `gen` path contains the code generated by the ent tool. It can **Not** be changed by human, it only contains the generated code. 
However, your `gen` path contains a folder named `schema`, which contains the definition of models by human hands. These code should be outside of `gen` path.
Please move the `schema` path out of `gen` path, then rerun the command, it would work.

**Comment by li31727** [comment]
First of all, the example of the ent official website is to create various models under the schema folder, and then the generated ent code is also in the same directory as the schema (https://entgo.io/zh/docs/getting-started)

I don't have any doubts about storing only the code automatically generated by ent in the gen directory, but I think that even if there is no schema.go in the schema folder, the program should not crash. What I expect is to skip this error without schema.go, and generate the relevant code of the factory normally, and finally output the folder information that is not generated on the console, instead of crashing the entire program

**Comment by lxy1992** [comment]
Sorry, my mistake. You are right, the schema path used to be the path generated by ent. It removed after version 0.11.X. So, when I tested it in new projects, it's all fine. I haven't test it in the old version of ent.
As you can see the README.md says, this tool only supports ent 0.11.4, and the Version Compatibility job is in the Todo list for a while. However, it's a good chance to move the first step to compatibility. I will fix it today. Thank you for your detail message. @li31727

**Comment by lxy1992** [comment]
@li31727  Sorry, my mistake. You are right, the schema path used to be the path generated by ent. It removed after version 0.10.X. So, when I tested it in new projects, it's all fine. I haven't test it in the old version of ent.
As you can see the README.md says, this tool only supports ent 0.11.4, and the Version Compatibility job is in the Todo list for a while. However, it's a good chance to move the first step to compatibility. I will fix it today. Thank you for your detail message. 

I guess you may wonder you are using the new version of ent, but still get a schema path in the `gen` path. It's because the project template used to migrate in ent version 0.9.X, then upgrade to the version 0.10. The ent tool won't remove these useless files and path, this should result in a fix in our god project.
